---

- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install unzip | Debian
  apt: name=unzip state=present
  when: ansible_os_family|lower == 'debian'

- name: Install unzip | RedHat
  yum: name=unzip state=present
  when: ansible_os_family|lower == 'redhat'

- name: Create consul-template directory structure
  file:
    dest:  "{{ item }}"
    owner: root
    group: root
    mode:  0755
    state: directory
  with_items:
    - "{{ consul_template_work_dir }}"
    - "{{ consul_template_conf_dir }}"
    - "{{ consul_template_log_dir }}"

- name: Copy vault ssl certificate
  copy:
    src: "{{ consul_template_vault_ssl.ca_cert.split('/')[-1] }}"
    dest: "{{ consul_template_work_dir }}/{{ consul_template_vault_ssl.ca_cert.split('/')[-1] }}"
  when: consul_template_vault_ssl.ca_cert is defined

- name: Copy template sources
  copy:
    src: "{{ item.source }}"
    dest: "{{ consul_template_work_dir }}/{{ item.source.split('/')[-1] }}"
  when: consul_template_templates
  with_items: "{{ consul_template_templates }}"
  
- name: Ensure consul-template bin directory exists
  file: dest={{ consul_template_bin_dir }} mode=0755 state=directory

- name: Ensure consul-template pid directory exists
  file: dest={{ consul_template_bin_dir }} mode=0755 state=directory

- name: Verify consul-template installed
  shell: >
      {{ consul_template_bin_dir }}/consul-template -version || true
  register: version

- debug: msg="{{ version.stderr }}"

- name: Set installed variable if version of consul-template is installed
  set_fact: installed=true
  when:  "'v' + consul_template_version in version.stderr.split(' ')"

- name: consul-template package install
  include_tasks: install.yml
  when: not installed|default(false)

- name: Create consul-template init script
  template:
    src:   consul-template.init.j2
    dest:  /etc/init.d/consul-template
    owner: root
    group: root
    mode:  0755
  when: ansible_service_mgr == 'upstart'
  notify: Restart consul-template

- name: Create consul-template systemd service script
  template:
    src:   consul-template.service.j2
    dest:  "{{ consul_template_systemd_units_dir }}/consul-template.service"
    owner: root
    group: root
    mode:  0644
  register: systemd
  when: ansible_service_mgr == 'systemd'
  notify: Restart consul-template

- name: Create consul-template defaults config file
  template:
    src:   defaults.conf.j2
    dest:  "{{ consul_template_conf_dir }}/defaults.conf"
    owner: root
    group: root
    mode:  0644
  notify: Reload consul-template

- name: Create consul-template logrotate config file
  template:
    src:   consul-template.logrotate.j2
    dest:  "/etc/logrotate.d/consul-template"
    owner: root
    group: root
    mode:  0644

- name: Reload systemd manager configuration
  command: systemctl daemon-reload
  when: systemd|changed

- name: Enable consul-template service
  service: 
    name: consul-template
    enabled: yes

- name: Start consul-template
  service: 
    name: consul-template
    state: started
  when: not consul_template_do_not_start_immediately

- name: consul-template template create
  include_tasks: template-config.yml
  when: consul_template_templates | default({})
  with_items: "{{ consul_template_templates }}"
